name: Build Docker images and push

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'release') ||
      github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        include:
          - arch: amd64
            docker_arch: x86_64
          - arch: arm64
            docker_arch: arm64
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get release version
      id: vars
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/heiher/natmap/releases/latest | jq -r .tag_name)
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="master"
        fi
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "Using version: $LATEST_TAG"

    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        platforms: linux/${{ matrix.arch }}
        build-args: |
          VERSION=${{ steps.vars.outputs.version }}
          ARCH=${{ matrix.docker_arch }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/natmap:${{ steps.vars.outputs.version }}-${{ matrix.arch }}
          ${{ secrets.DOCKER_USERNAME }}/natmap:latest-${{ matrix.arch }}
